### ISSUE TITLE
Length of refresh token Expiration

### ISSUE THREAD

**Issue by vikramkh** [wp-graphql/wp-graphql-jwt-authentication#100]
How long does the refresh token last?

**Comment by jasonbahl** [comment]
The default is 5 minutes and there's a filter to override it. 

See: https://github.com/wp-graphql/wp-graphql-jwt-authentication#change-auth-token-expiration

**Comment by vikramkh** [comment]
@jasonbahl I think that’s for the auth token. Is the refresh token forever?

**Comment by jasonbahl** [comment]
@vikramkh ah, I apologize. Read that too fast. 

The refresh token is default at 1 year.
