### ISSUE TITLE
Token validation fails

### ISSUE THREAD

**Issue by videomugre** [wp-graphql/wp-graphql-jwt-authentication#106]
When get_secret_key() gets called at line [557](https://github.com/wp-graphql/wp-graphql-jwt-authentication/blob/develop/src/Auth.php#L557) of Auth.php, the function doesn't find `GRAPHQL_JWT_AUTH_SECRET_KEY ` nor the filter `graphql_jwt_auth_secret_key`, so we end up with a `NULL` value.

Also, I think `! empty( GRAPHQL_JWT_AUTH_SECRET_KEY )` will always return true even if it's not defined, just like happens in the case above.

**Comment by jasonbahl** [comment]
you need to define a secret as described in the Install & Activate step: https://github.com/wp-graphql/wp-graphql-jwt-authentication#install-activate--setup

Without it, you'd be easily exposing your site to vulnerabilities.

**Comment by jasonbahl** [comment]
I'm going to close this as I believe my previous comment resolves this, but if not let me know and we can re-open.

**Comment by videomugre** [comment]
Yeah that's the issue, I try to define my secret key with both methods, but it's nowhere to be found when the function `get_secret_key` is specifically called at line 557 of Auth.php. Every other method finds it, I have no idea why, even `array_key_exists('graphql_jwt_auth_secret_key' , $GLOBALS['wp_filter'])` returns false.

**Comment by jasonbahl** [comment]
@videomugre where are you including your filter? Perhaps you're adding your filter somewhere that's not executing or you're adding it too late?

**Comment by videomugre** [comment]
I tried to define `GRAPHQL_JWT_AUTH_SECRET_KEY` in wp.config.php and in the functions.php of my theme attached to a `init` hook. The filter also was also added in the functions.php of my theme, at the top of the script.

**Comment by videomugre** [comment]
I'll try later today, but still, why the other times `get_secret_key` is used there's no issue? since I was able to login with my secret key for the longest time I had no idea what was going on haha.
