### ISSUE TITLE
filter to change authToken expiration date doesn't work

### ISSUE THREAD

**Issue by alexadark** [wp-graphql/wp-graphql-jwt-authentication#109]
I tried that 
`add_filter('graphql_jwt_auth_expire', 60);`
also with other times, and then the token expires immediately

**Comment by henrikwirth** [comment]
I adjusted the documentation:

```
function custom_jwt_expiration( $expiration ) {
    return 60;
}

add_filter('graphql_jwt_auth_expire', 'custom_jwt_expiration', 10);
```

I guess this can be closed then, if not let me know and I reopen it ✌️

**Comment by nagman** [comment]
Mmh... doesn't seem to work for me :/
