### ISSUE TITLE
Get a token for an anonymous user session.

### ISSUE THREAD

**Issue by chrispytoes** [wp-graphql/wp-graphql-jwt-authentication#117]
I'm trying to figure out building a WooCommerce site on Gatsby. The only thing I'm confused on is how I can get a session token for an anonymous user to add items to their cart and checkout without logging in. I dug around in this [Gatsby WooCommerce theme](https://gatsby-woocommerce-theme.netlify.app/). If I add an item to the cart without logging in, it's still able to make the request to the GraphQL API, and add the item to my cart. In my inspector I can see that a header called `woocommerce-session`, which contains a JWT, is being sent on all the GraphQL requests, but I can't figure out how to actually obtain one without signing in.

How can I retrieve an access token for anonymous user session? Does this theme do something special or is this possible using this plugin?

**Comment by muhaimincs** [comment]
hello @chrispytoes, how did you solve it?

**Comment by Emiliano-Bucci** [comment]
@chrispytoes Hi! Did you manage to solve this?

**Comment by chrispytoes** [comment]
@Emiliano-Bucci @muhaimincs I solved it by switching to Next.js 🤣

**Comment by Emiliano-Bucci** [comment]
@chrispytoes Could you please elaborate a bit more? Currently i will implement a similar logic using NextJs, and i don't know how to generate a token for anonymous users to pass to Woocommerce.

**Comment by chrispytoes** [comment]
@Emiliano-Bucci It's not a static site anymore. It is a live running Next.js application using server-side authentication directly with the json API.

**Comment by Emiliano-Bucci** [comment]
So you're not handling the anonymous user case. Ok.
