### ISSUE TITLE
All requests sent with a fresh auth token return both a 403 AND the correct query results.

### ISSUE THREAD

**Issue by jeslenbucci** [wp-graphql/wp-graphql-jwt-authentication#139]
This is super confusing. 

I'm using VueJS + NuxtJS + Apollo via the Nuxt-Vue-Apollo Module. When I send my initial login mutation to the server, I correctly receive both the authentication and refresh tokens. My authentication token is then sent for every subsequent graphql call.

The first query with the auth header happens immediately after login when I fetch a bunch of required data using the `viewer` type. The request "fails" by returning a 403, but then within the network error, when doing custom error handling with apollo, the correct result is also returned. 

I'm pretty sure everything was working yesterday. However, I was recently trying out some other JWT plugins, and I'm not sure if it's possible that one of those is interfering with this. I have also changed the `graphql_jwt_auth_secret_key` using both the filter and the PHP definition.

**Comment by ryntab** [comment]
For anyone looking into this issue, here is a small checklist of things to try. 

1.  Deactivate any other JWT token plugins that may be active including those for the REST-API
2. Make sure you are not sending refresh token requests in multiples or refreshing tokens before a new one is set.
