### ISSUE TITLE
Spinning wheel of death on WPGraphQL after install + Breaks website with 500 error

### ISSUE THREAD

**Issue by dgallardox** [wp-graphql/wp-graphql-jwt-authentication#152]
**Problem symptom #1** - After install of this plugin, the WPGraphQL interface will not load. It is stuck on the loading wheel but never loads.

<img width="1340" alt="Screen Shot 2022-04-07 at 1 51 20 PM" src="https://user-images.githubusercontent.com/101141475/162275813-1371fe77-2e54-4388-acd8-7c63a9f131bb.png">

**Problem symptom #2** - After install of this plugin, assuming in relation to the previous error. My local build receives "Response not successful" 500 error. 

<img width="948" alt="Screen Shot 2022-04-07 at 1 53 49 PM" src="https://user-images.githubusercontent.com/101141475/162276366-a2ed60c7-3f1f-43d6-8186-fd5cd011fb67.png">

**Comment by eavonius** [comment]
I'm seeing the same. Anyone have a newer fork with more recent compatibility, or is this plugin abandoned?

**Comment by eavonius** [comment]
@dgallardox I'm not sure if you had the same problem, but after checking the debug logs it wasn't picking up the JWT secret key. When it does this, it spins like that. Once I made sure GRAPHQL_JWT_AUTH_SECRET_KEY was set with a unique key and restarted Apache, it worked fine!

**Comment by LZL0** [comment]
@eavonius is correct, you need to define an token with `define( 'GRAPHQL_JWT_AUTH_SECRET_KEY', 'your-secret-token' );`
You can generate one at https://api.wordpress.org/secret-key/1.1/salt/

**Comment by jasonbahl** [comment]
I just published v0.5.0 (https://github.com/wp-graphql/wp-graphql-jwt-authentication/releases/tag/v0.5.0) which resolves this issue, even if you haven't set up the Auth Secret yet.

I'm going to close this as I confirmed the issue, and the resolution, but if you're having issues after updating to v0.5.0, open another issue, reference this one, and provide steps to reproduce.
