### ISSUE TITLE
Critical Error: Status Code 500

### ISSUE THREAD

**Issue by dgallardox** [wp-graphql/wp-graphql-jwt-authentication#154]
Perhaps I am doing something wrong; But now, even if a token is defined or not, I get a critical site error right after activating the plugin. This happens for version 5.0 and the current repo.

![Screen Shot 2022-04-18 at 11 44 49 AM](https://user-images.githubusercontent.com/101141475/163845675-560d000c-25af-4286-9e1e-53606f6beeac.png)

![Screen Shot 2022-04-18 at 11 45 44 AM](https://user-images.githubusercontent.com/101141475/163845682-9f41c2a5-42fc-40a9-967c-6829ed9ec0c0.png)

**Comment by RodrigoTomeES** [comment]
Same error here

<img width="805" alt="imagen" src="https://user-images.githubusercontent.com/13077343/163959952-c52cbe4b-8b54-4af2-a913-89251406e65e.png">

**Comment by stefkudla** [comment]
I get the same error as above

**Comment by evangelinepapanicola** [comment]
Same here!

**Comment by markkelnar** [comment]
What version of PHP are you running?

**Comment by markkelnar** [comment]
I'm thinking the zip release composer autoload map was built with references to the codeception dev tools. I'll confirm and get back.

**Comment by jasonbahl** [comment]
Thanks all for reporting, and thanks @markkelnar for the fix!

I've release v0.5.1 which should no longer have this error: https://github.com/wp-graphql/wp-graphql-jwt-authentication/releases/tag/v0.5.1
