### ISSUE TITLE
Cannot query field jwtRefreshToken

### ISSUE THREAD

**Issue by Khadreal** [wp-graphql/wp-graphql-jwt-authentication#163]
I'm trying to query the viewer endpoint to get `jwtRefreshToken`, this is my query
```
query RequestAuthRefreshToken {
      viewer {
        id
        jwtRefreshToken
      }
}
```
I got this error
```
{
  "errors": [
    {
      "message": "Cannot query field \"jwtRefreshToken\" on type \"User\".",
      "extensions": {
        "category": "graphql"
      },
      "locations": [
        {
          "line": 4,
          "column": 9
        }
      ]
    }
  ],
  "extensions": {
    "debug": []
  }
}
```
Please any idea what the issue is

**Comment by ojohnny** [comment]
@Khadreal Please provide more information of your setup.

- Which version of wp-graphql-jwt-authentication?
- Which version of WP GraphQL?
- Which version of WordPress?
- Which version of PHP?

I can't reproduce this issue with wp-graphql-jwt-authentication 0.5.2, WP GraphQL 1.8.2, WordPress 6.0, and any of PHP 7.4, 8.0, or 8.1.

**Comment by Khadreal** [comment]
Thanks @ojohnny,

wp-graphql-jwt-authentication -- 0.5.2
wp-graphql -- 1.8.2
WordPress -- 5.9.3
PHP -- 7.4.29

**Comment by Khadreal** [comment]
I think the issue was from my end, I was trying to add `jwtRefreshToken`  to another node using `graphql_jwt_user_types` filter, commenting it out added it back to viewer.

Thanks @ojohnny
