### ISSUE TITLE
Document Authorization header requirement

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wp-graphql-jwt-authentication#19]
It appears that many folks have setup WordPress in a way that doesn't allow HTTP Authorization headers to make it to WordPress. 

See this conversation here: https://wp-graphql.slack.com/files/UA31D33V0/FA58KUQFQ/jwt-record-2018-04-10_20.13.40.mp4

In this particular case, the solution was to adjust an Apache setting to allow the proper headers to make it to WordPress. I believe in someone else's case, their Docker environment was blocking the headers. 

The issue should be called out in the README explaining that HTTP_Authorization headers _must_ be supported at the network layer for this plugin to work. 

WordPress environments can be spun up in endless ways, so we can't document _all_ possibilities for making this work, but can at least call out the general requirement and point folks in the right direction for enabling it for their environment.

**Comment by henrikwirth** [comment]
@jasonbahl I believe this is addressed in the Readme and can be closed.

**Comment by henrikwirth** [comment]
I'll close this, as it has been stated in the readme.
