### ISSUE TITLE
Plugin breaks upon activation

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wp-graphql-jwt-authentication#2]
see: https://github.com/wp-graphql/wp-graphql/issues/262#issuecomment-341901334

----

@towfiqi I created an issue to track on this repo for Auth stuff. 

Looking into why this won't activate now. 🤔

**Comment by jasonbahl** [comment]
@towfiqi did you `define('GRAPHQL_JWT_AUTH_SECRET_KEY', 'your-top-secrect-key');` like mentioned in the README? 

https://github.com/wp-graphql/wp-graphql-jwt-authentication#configuration--activation


I'll make sure things fail more gracefully, but I _believe_ if you define that key you should be good.

I'll work on cleaning up the code, writing tests and docs today hopefully. . .but try defining the secret for now and see if that works.

**Comment by towfiqi** [comment]
Yes I did set it.

**Comment by jasonbahl** [comment]
@towfiqi I basically rewrote the plugin and have 100% unit test coverage now. . .I also updated the README. I think _most_ things are about the same,  but read through again. 

Let me know if you're still having issues activating or if things are working now.

**Comment by jasonbahl** [comment]
@towfiqi also, if you're interested, we have a Slack for WPGraphQL so we can communicate in real-time when necessary. You can join here: https://www.wpgraphql.com/community/

**Comment by jasonbahl** [comment]
@towfiqi I believe this is resolved, so I'm going to close this, but if you're still having the issue, feel-free to re-open with more details or open a new issue. Thanks!

**Comment by muhaimincs** [comment]
Hello @jasonbahl ... I'm new to the wordpress. Where do I set the secret? Thanks in advance
