### ISSUE TITLE
expose Refresh auth in response headers

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wp-graphql-jwt-authentication#22]
When making an authenticated request, a JWT Refresh token should be provided in the response headers. 

This allows clients to take the token from the response and update their local cached copy.

**Comment by ManUtopiK** [comment]
Thanks for the plugin !
I'm learning JWT authentication and I'm confuse about how it really works.
I think i made everything good, but my current implementation loose connection and throw the error "No user was found with the provided ID" after few minutes. So I found an expiration time at [Auth.php#L105](https://github.com/wp-graphql/wp-graphql-jwt-authentication/blob/master/src/Auth.php#L105).  This is 5 minutes! But in my apollo client, I set 7 days with `await this.$apolloHelpers.onLogin(res.login.authToken, undefined, 7)` ?

I read a little bit more about jwt and found this response in security stackexchange: [why refresh tokens are used](https://security.stackexchange.com/questions/116771/why-refresh-tokens-are-used?rq=1)
So apparently, 15 minutes is more common. Also, we need a refresh token of course. Do you plan to work on this feature ? What's your strategy about jwt ?
