### ISSUE TITLE
Unreachable code when looking for Authorization headers

### ISSUE THREAD

**Issue by thisischrisj** [wp-graphql/wp-graphql-jwt-authentication#24]
In reference to #16 , there is an issue with Auth.php .

I'm using MAMP too and the bearer token can be found in $_SERVER['REDIRECT_HTTP_AUTHORIZATION'] . The function get_auth_header looks for this as a back-up but never uses it. Looking at the line:

`$auth_header = isset( $auth_header ) ? $auth_header : ( isset( $redirect_auth_header ) ? $redirect_auth_header : null );`

You'll see that the test for isset($auth_header) will always return true (as the variable is set to false on failure) so the  isset( $redirect_auth_header ) part is never reached. Instead, the line should be:

`$auth_header = $auth_header !== FALSE ? $auth_header : ( $redirect_auth_header !== FALSE ? $redirect_auth_header : null );`

**Comment by OnekO** [comment]
I saw the same error, would be nice to fix it.

**Comment by henrikwirth** [comment]
I guess this has been closed by #37 
If not, please let us know @thisischrisj
