### ISSUE TITLE
TypeError being thrown

### ISSUE THREAD

**Issue by CodeProKid** [wp-graphql/wp-graphql-jwt-authentication#32]
Seeing a bunch of TypeError's being thrown from this plugin.

Error Message: 
TypeError: Uncaught exception 'TypeError' with message 'Argument 1 passed to WPGraphQL\JWT_Authentication\ManageTokens::add_auth_headers_to_rest_response() must be an instance of WP_HTTP_Response, array given, called in /var/www/wp-includes/class-wp-hook.php on line 286' in /var/www/wp-content/client-mu-plugins/plugins/wp-graphql-jwt-authentication/src/ManageTokens.php:321

Stack Trace:
…auth_headers_to_rest_response called at /var/www/wp-includes/
class-wp-hook.php (286)
in WP_Hook::apply_filters called at /var/www/wp-includes/plugin.php (208)
…apply_filters called at /var/www/wp-includes/rest-api/
class-wp-rest-server.php (970)
…ver::dispatch called at /var/www/wp-includes/rest-api/
class-wp-rest-server.php (329)
in WP_REST_Server::serve_request called at /var/www/wp-includes/rest-api.php (309)
in rest_api_loaded called at /var/www/wp-includes/class-wp-hook.php (286)
in WP_Hook::apply_filters called at /var/www/wp-includes/class-wp-hook.php (310)
in WP_Hook::do_action called at /var/www/wp-includes/plugin.php (531)
in do_action_ref_array called at /var/www/wp-includes/class-wp.php (387)
in WP::parse_request called at /var/www/wp-includes/class-wp.php (737)
in WP::main called at /var/www/wp-includes/functions.php (1105)
in wp called at /var/www/wp-blog-header.php (16)
in require called at /var/www/index.php (17)

**Comment by jasonbahl** [comment]
closed by: https://github.com/wp-graphql/wp-graphql-jwt-authentication/commit/5ad5333536a244691d2b35886583f628ddef5d41
