### ISSUE TITLE
"Internal server error" in login mutation after upgrading to wp-graphql v 0.3

### ISSUE THREAD

**Issue by szvest** [wp-graphql/wp-graphql-jwt-authentication#34]
I am getting `"Internal server error"` in login mutation after upgrading to wp-graphql v 0.3. 

Is it coming from `'user' => DataSource::resolve_user( $user->data->ID )`?

**My mutation** 

```
mutation loginAndGetTokenAndUser($username: String!, $password: String!) {
  login(
    input: {
      clientMutationId: "gonzo"
      username: $username
      password: $password
    }
  ) {
    authToken
    refreshToken
    user {
      id
      userId
    }
  }
}
```
**The error**
```
{
  "errors": [
    {
      "message": "Internal server error",
      "category": "internal",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "login"
      ]
    }
  ],
  "data": {
    "login": null
  }
}
```

**Comment by jasonbahl** [comment]
@szvest ah this was merged already, I need to do a release.

**Comment by jasonbahl** [comment]
see: https://github.com/wp-graphql/wp-graphql-jwt-authentication/pull/33

**Comment by szvest** [comment]
Works as expected with the `$context`  argument (`\WPGraphQL::get_app_context(`)).

**Comment by henrikwirth** [comment]
This is fixed in #33 
Therefore I'll close it. Let us know if something related to this issue comes up again.

**Comment by vana-dev** [comment]
same problem, fresh wp installation

**Comment by raghavSrih** [comment]
I have the same issue as well "

debugMessage": "Cookie nonce is invalid"

**Comment by raghavSrih** [comment]
I have to logout and login to my wordpress. It solved the isue

**Comment by raghavSrih** [comment]
I had to logout and log back in Wordpress account.
