### ISSUE TITLE
Decrease priority of \WPGraphQL\JWT_Authentication\init

### ISSUE THREAD

**Issue by mwidmann** [wp-graphql/wp-graphql-jwt-authentication#35]
I'm not 100% sure how this should be addressed, but I spent the last hour trying to identify why using the just generated JWT returned that the user needed to login when calling the `viewer` query.

In the end it turns out that another plugin [elasticpress](https://github.com/10up/ElasticPress) also hooked into `plugins_loaded`´and called `is_user_logged_in()` which in turn called the `determine_current_user` hook before wp-graphql-jwt-authentication was able to register the filter. 

The determination of the current user is only performed exactly once and so the JWT was never matched into an actual user.

My fix was to lower the priority of the `plugins_loaded` hook to 9 (default is 10) on line 205 of wp-graphql-jwt-authentication.php

```php
add_action( 'plugins_loaded', '\WPGraphQL\JWT_Authentication\init', 9 );
```

**Comment by jasonbahl** [comment]
@mwidmann interesting issue. I'll check it out and confirm your solution or see if I have any alternative ideas.

**Comment by OnekO** [comment]
I had the same problem, not sure which plugin was the problem, but it solved updating the priority. Thanks @mwidmann

**Comment by henrikwirth** [comment]
It seems that this can be closed. The priority now is set to 1 instead of default (10), which should fix the Issue.

**Comment by jonlovera** [comment]
I was having the same issue, this time by a different plugin called [flexible-shipping](https://wordpress.org/plugins/flexible-shipping/). It looks like they use `is_user_logged_in()` as well. 

The interesting part is that they use negatives numbers for their `plugins_loaded` actions (like `-35`). So changing the `plugins_loaded` for GraphQL JWT to `-100` fixed it. 

@jasonbahl @henrikwirth the questions now would be
- Do we make it negative by default something like `-1000` or `-300`? 
- Do we add a constant that can change this variable similar to `GRAPHQL_JWT_AUTH_SECRET_KEY`?
