### ISSUE TITLE
Conflicts with "the events calendar"

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wp-graphql-jwt-authentication#39]
When "The Events Calendar" plugin is active at the same time as this plugin, the current user appears to never be set. 

I did a screenshare with @mhinton to debug, and then did some research after. 

Here's some notes from our slack conversation for context:

jasonbahl [4:17 PM]
> yo!
> got a lead
> not sure _why_ but it looks like if you comment out line 280 on `the-events-calendar/common/src/Tribe/Main.php` things work
still trying to understand _why_
but this line `tribe( Tribe__Admin__Help_Page::class )->register_assets();` appears to be the culprit

Matthew [4:21 PM]
> So just commenting out the-events-calendar/common/src/Tribe/Main.php line 277 lets me create a post now.

jasonbahl [4:33 PM]
> ok, following the trail, it seems like a bit deeper, the culprit might be `wp_create_nonce( 'sysinfo_optin_nonce' )` in `the-events-calendar/common/src/Tribe/Admin/Help_Page.php`
if I comment out `'sysinfo_optin_nonce'   => wp_create_nonce( 'sysinfo_optin_nonce' )` things work

jasonbahl [4:46 PM]
> I think there's _some_ conflict with `determine_current_user` happening
:thinking_face:

Matthew [4:46 PM]
> Yeah `sysinfo_optin_nonce` seems to be part of the issue. I don’t really see why at the moment.

jasonbahl [4:54 PM]
> I think I'm making _some_ progress on some changes I can make in the JWT Auth plugin.
I'll touch base again tomorrow

Matthew [4:55 PM]
> That’s great, thanks.

jasonbahl [5:02 PM]
> ok, ya, I think I have a resolution figured out, but need to do some testing. Getting dinner with the family, but I think I have a solution
crazy issue

**Comment by jasonbahl** [comment]
@mhinton, I pushed another update to this PR #40 

I have things working locally with that PR + The Events Calendar active, but would be good for you to also confirm. 

Attached are a few screenshots.

### BROKEN: current master branch checked out along with "The Events Calendar" active
![Screen Shot 2019-07-18 at 11 37 31 AM](https://user-images.githubusercontent.com/1260765/61479245-a9a2b000-a950-11e9-8b70-46c43e4e3c7a.png)


### WORKING: This PR checked out along with "The Events Calendar" active

![Screen Shot 2019-07-18 at 11 37 49 AM](https://user-images.githubusercontent.com/1260765/61479285-be7f4380-a950-11e9-8db8-b6b56f0497f3.png)

**Comment by jasonbahl** [comment]
^ I'm not thrilled with the state of the code in this PR still, but if we can confirm it's working, I'll clean a few things up

**Comment by mhinton** [comment]
I can now get authorized and run mutations on the server. Thanks for working with me on this.

**Comment by jasonbahl** [comment]
@mhinton whoohooo!!!!

I'll get this merged in and prep a release. 

Thanks for the follow up!

**Comment by guilhermejbranco** [comment]
@jasonbahl I'm having this issue again (with Events Calendar v5.2), and as you mentioned:

> not sure why but it looks like if you comment out line 280 on the-events-calendar/common/src/Tribe/Main.php things work
> still trying to understand why
> but this line tribe( Tribe__Admin__Help_Page::class )->register_assets(); appears to be the culprit

commenting out this line (now on line 269), makes things work again.

**Comment by guilhermejbranco** [comment]
#107
