### ISSUE TITLE
JWT fields cannot be retrieved via viewer query

### ISSUE THREAD

**Issue by mlipscombe** [wp-graphql/wp-graphql-jwt-authentication#41]
The following query fails:

```graphql
{
  viewer {
    userId
    jwtAuthToken
    jwtRefreshToken
  }
}
```

with this error:
`Argument 1 passed to WPGraphQL\\JWT_Authentication\\ManageTokens::WPGraphQL\\JWT_Authentication\\{closure}() must be an instance of WP_User, instance of WPGraphQL\\Model\\User given`.

**Comment by jasonbahl** [comment]
@mlipscombe checking this out now

**Comment by jasonbahl** [comment]
@mlipscombe I just merged a fix for this. Let me know if it's still causing issues and we can re-open or file a new issue.
