### ISSUE TITLE
Error! Network error: Response not successful: Received status code 403

### ISSUE THREAD

**Issue by webface** [wp-graphql/wp-graphql-jwt-authentication#44]
I am running the latest version of the plugin on the latest wordpress. With the plugin I am able to login a user and get an auth token. I'm facing a few issues

1. When I go to activate protected api I get the following error in my react application:
Error! Network error: Response not successful: Received status code 403
Not even the login route would work anymore. How do you restrict all content in wpgraphql and allow only queryies and mutations like forgot password, login, register etc. Right now this plugin just kicks everyone out. Another strange thing is that despite this, the data is still beign returned to the console.

2. On the topic of securing routes,..I used this example:
[https://www.wpgraphql.com/2019/01/30/preventing-unauthenticated-requests-to-your-wpgraphql-api/](url) but it also does not get_current_user_id() when the user has logged in so please help

**Comment by webface** [comment]
3. There should be setting to configure what should be public and private and or a filter to make compatible with other plugins

**Comment by MoOx** [comment]
I just wanted to add login capabilities to my static website, especially so my main author can see drafts WIP. So according to WP default restrictions, only logged user can access drafts (which make sense). So I am facing the same issue:
- I am successfully able to log, get a token, store it in local storage & send it via the Authorization header with `Bearer ${token}`
- At first, it didn't worked, I read carefully README, then find the `SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1` to add in my htaccess.
- As soon as I did that, I started facing 403 http code for all request.

Pretty weird, especially when you see that response have the actual content when there is not restrictions (eg: list of post, response contains the normal list etc).

Any workaround this @jasonbahl ? Can we help improve the situation? I have to put in production my projet, and this draft preview trick I need to do is my missing piece 😅

**Comment by MoOx** [comment]
I actually was able to make this work. 403 wasn't clear for... Ooopsy :)
Now I am good!

**Comment by ivanjeremic** [comment]
> I actually was able to make this work. 403 wasn't clear for... Ooopsy :)
> Now I am good!

Can you also share with us how you fixed this error please? I'm facing currently the same error in the gatsby-kanban demo @jasonbahl has made.

**Comment by MoOx** [comment]
403 means you need to reconnect, if I am correct.

So I ended up using something like this:

```js
const MUTATION_REFRESH_ACCESS_TOKEN = gql`
  mutation refreshAccessToken(
    $RefreshJwtAuthTokenInput: String!
    $clientMutationId: String!
  ) {
    refreshJwtAuthToken(
      input: {
        jwtRefreshToken: $RefreshJwtAuthTokenInput
        clientMutationId: $clientMutationId
      }
    ) {
      authToken
    }
  }
`;
export const refreshAccessToken = RefreshJwtAuthTokenInput => {
  return apolloClient
    .mutate({
      mutation: MUTATION_REFRESH_ACCESS_TOKEN,
      variables: {
        RefreshJwtAuthTokenInput,
        clientMutationId: "refreshAccessToken",
      },
    })
    .then(({ data }) => {
      return data.refreshJwtAuthToken.authToken;
    })
    .catch(() => {
      return null;
    });
};

const errorLink = onError(({ networkError, operation, forward }) => {
  if (networkError.statusCode === 403 && store.refreshToken) {
    store.authToken = undefined;
    return new Observable(observer => {
      refreshAccessToken(store.refreshToken)
        .then(authToken => {
          if (!authToken) {
            logout();
          } else {
            store.authToken = authToken;
            saveStore();
            operation.setContext(({ headers }) => {
              return {
                headers: {
                  ...headers,
                  authorization: "Bearer " + store.authToken,
                },
              };
            });
          }
          const subscriber = {
            next: observer.next.bind(observer),
            error: observer.error.bind(observer),
            complete: observer.complete.bind(observer),
          };
          // Retry last failed request
          forward(operation).subscribe(subscriber);
        })
        .catch(err => {
          logout();
          observer.error(err);
        });
    });
  }
});
```

Then the `errorLink` is send to `ApolloClient` `link` option

```js
function create(initialState) {
  return new ApolloClient({
    connectToDevTools: isBrowser,
    ssrMode: !isBrowser,
    link: middlewareLink.concat(errorLink).concat(httpLink), // <===== HERE
    cache: new InMemoryCache({
      fragmentMatcher: new IntrospectionFragmentMatcher({
        introspectionQueryResultData: require("./introspectionQueryResult.json")
          .data,
      }),
    }).restore(
      initialState || (isBrowser ? window.__APOLLO_STATE__ : undefined ||
        {},
    ),
  });
}
```

**Comment by henrikwirth** [comment]
Seems that this problem was due to the time limit the Auth token has, which is set to 5 Minutes.
As @MoOx explained. You need to refresh the Token with the `refreshJwtAuthToken` mutation. How you do it is dependent on your client side implementation.

Hope this solves it for everyone. I gonna go ahead and close this for now. If there is something still unsolved, let us know.
