### ISSUE TITLE
Get token for current user?

### ISSUE THREAD

**Issue by homerjam** [wp-graphql/wp-graphql-jwt-authentication#58]
Hi,

Is there a way to generate a token for the currently logged in user? For example I'd like to write a filter that appends this to the preview URL (which links out to a PWA on another domain) so that a user can view an unpublished post.

Unless there's something I'm missing and there's a better way to go about it?

Edit: perhaps [this](https://github.com/wp-graphql/wp-graphql-jwt-authentication/blob/4dacc6f37f0dd2f25c9e86cfb7639b3c212ed640/src/Auth.php#L128) is what I need? Is there an example of how to use it anywhere?

Thanks,
James

**Comment by homerjam** [comment]
Nevermind!


```php
$auth = new WPGraphQL\JWT_Authentication\Auth;

$token = $auth->get_token(wp_get_current_user());

add_filter('preview_post_link', 'auth_preview_link');
add_filter('preview_post_link', 'auth_preview_link');
function auth_preview_link($link)
{
    return $link . '?authToken=' . $token;
}
```

**Comment by muhaimincs** [comment]
hi @homerjam, may I know how did you manage this? what file to set up?
