### ISSUE TITLE
AuthTokens only valid for 10-15mins

### ISSUE THREAD

**Issue by joshatoutthink** [wp-graphql/wp-graphql-jwt-authentication#65]
How long should AuthTokens last.  My tokens are only being valid for 10-15 minutes and then I need to re-login. Is this the standard duration? How do I extend the duration.

here is my mutation
```
export const LOGIN_MUTATION = gql`
  mutation LOGIN_MUTATION($username: String!, $password: String!) {
    userLogin: login(
      input: {
        username: $username
        password: $password
        clientMutationId: "blah"
      }
    ) {
      authToken
      user {
        username
        id
        name
        nickname
        email
      }
    }
  }
`
```
and im using apollo hooks
```
const [userLogin, { loading, error, data }] = useMutation(LOGIN_MUTATION, {
    variables: {
      username: form.username,
      password: form.password,
    },
    onCompleted({ userLogin }) {
      typeof window !== "undefined" &&
        localStorage.setItem("token", userLogin.authToken)
      localStorage.setItem("userID", userLogin.user.id)
      navigate("/dashboard")
    },
    update(cache, payload) {
      const data = cache.readQuery({ query: CURRENT_USER })
      const { viewer } = data
      const UserLoggedIn = { ...payload.data.userLogin.user }
      data.viewer = UserLoggedIn
      cache.writeQuery({ query: CURRENT_USER, data })
    },
  })
```

In the wp side of things I have just followed the docs to set up the plugin.

**Comment by joshatoutthink** [comment]
Oh I just read in another issue that the authTokens only last 5 minutes. Is there any way to extend that?

**Comment by joshatoutthink** [comment]
I tried using this but doesnt seemed to have worked

add_filter( 'graphql_jwt_auth_expire', function($expiration){
        $expiration = Auth::get_token_issued() + 31536000;
        return $expiration;
    }, 100);

**Comment by henrikwirth** [comment]
Hi @joshatoutthink this is the correct behaviour for Auth Tokens. What you would need to do is a silent refresh with the Refresh Token. The Refresh Token should stay valid for a long period. 

Checkout the repo I just started about this and the Epic I created, trying to break down the Auth Flow: https://github.com/NeverNull/gatsby-apollo-wpgraphql-jwt-starter/issues/1

Also, in the epic you can find some links to articles, that describe how it should be implemented.

**Comment by joshatoutthink** [comment]
Thanks this is really helpful!
