### ISSUE TITLE
JWT token could not be returned

### ISSUE THREAD

**Issue by henrikwirth** [wp-graphql/wp-graphql-jwt-authentication#69]
There seems to be a bug with the newest versions:

WPGraphQL: 0.6.1
JWT: 0.3.5

When doing the `registerUser` mutation like so:

```
mutation RegisterUser($input: RegisterUserInput!) {
  registerUser(input: $input) {
    user {
      jwtAuthExpiration
      jwtUserSecret
      jwtRefreshToken
      isJwtAuthSecretRevoked
      jwtAuthToken
    }
  }
}
```

The user gets registered, but the response is the following:

```
{
  "errors": [
    {
      "message": "The user secret could not be returned",
      "category": "user",
      "locations": [
        {
          "line": 5,
          "column": 7
        }
      ],
      "path": [
        "registerUser",
        "user",
        "jwtUserSecret"
      ]
    },
    {
      "message": "The JWT token could not be returned",
      "category": "user",
      "locations": [
        {
          "line": 6,
          "column": 7
        }
      ],
      "path": [
        "registerUser",
        "user",
        "jwtRefreshToken"
      ]
    },
    {
      "message": "The JWT token could not be returned",
      "category": "user",
      "locations": [
        {
          "line": 8,
          "column": 7
        }
      ],
      "path": [
        "registerUser",
        "user",
        "jwtAuthToken"
      ]
    }
  ],
  "data": {
    "registerUser": {
      "user": {
        "jwtAuthExpiration": "1580566063",
        "jwtUserSecret": null,
        "jwtRefreshToken": null,
        "isJwtAuthSecretRevoked": false,
        "jwtAuthToken": null
      }
    }
  }
}
```

So it seems for some reason inside [ManageTokens.php](https://github.com/wp-graphql/wp-graphql-jwt-authentication/blob/develop/src/ManageTokens.php) the following calls don't work as intended:
- Auth::get_user_jwt_secret
- Auth:: get_token
- Auth:: get_refresh_token

Also the error message of refresh token should be different to the one from the token.

**Comment by jasonbahl** [comment]
@henrikwirth just to clarify, this mutation was working on previous versions just fine? Is this a regression or something that's been broken for a while?

**Comment by henrikwirth** [comment]
It works fine with the versions described here: https://github.com/NeverNull/gatsby-apollo-wpgraphql-jwt-starter#gatsby-apollo-wpgraphql-jwt-starter

**Comment by jasonbahl** [comment]
@henrikwirth ok thanks. That helps. I'll see what I can find out!
