### ISSUE TITLE
Increase accessToken expiry

### ISSUE THREAD

**Issue by MitchEff** [wp-graphql/wp-graphql-jwt-authentication#82]
Look, I mean I _get_ that it's super secure for a token to only last a couple of minutes, but it's also an enormous pain. Refreshing it pretty much any time a user does anything makes the system hang and feel slow. 

I can see some mentions here and there about changing the expiry, but nowhere is it documented how to do so. Is it possible to just make it like, ten billion years or something? If so, how do I do that?

**Comment by jasonbahl** [comment]
I would definitely recommend sticking to a 2-token flow where the auth token has a short life and the refresh token is used to get a new token. If an auth token with a long life is compromised someone could do a lot of malicious damage to your server. 

That said, there is this filter to make the expiration whatever you want for your setup: https://github.com/wp-graphql/wp-graphql-jwt-authentication/blob/develop/src/Auth.php#L115

**Comment by MitchEff** [comment]
I don't suppose there's any example usage or anything? 

The default value is set by get_token_issued() and adding 300 seconds, but outside of this function I'm not going to have get_token_issued().

**Comment by henrikwirth** [comment]
I believe this change would fix it: https://github.com/wp-graphql/wp-graphql-jwt-authentication/commit/9161fc5848ba07ce0e16063d8496c9d92352c1a9

Need to get a PR going for it.

**Comment by MitchEff** [comment]
Yeah that certainly looks like it. I'm just going to copy that into mine for now, it's perfect.
