### ISSUE TITLE
Expose auth token in response headers

### ISSUE THREAD

**Issue by kellenmace** [wp-graphql/wp-graphql-jwt-authentication#98]
We should expose auth token in response headers so it can be used to update the auth token stored on the client, similar to what's shown in this Apollo link: https://github.com/benawad/slack-clone-client/blob/31_fix_auto_refresh_of_jwt_tokens/src/apollo.js#L18-L36

We are doing this already with the refresh token. PR is below.

**Comment by kellenmace** [comment]
For anybody finding this issue via search –

Using this plugin with Apollo Client, the code for taking the auth token and refresh tokens from the response to update the tokens stored on the client ends up looking like this:

```javascript
/**
 * Update the client-side authToken and refreshToken with the
 * updated tokens sent back in the response headers.
 */
const authTokenUpdateLink = new ApolloLink((operation, forward) => {
  return forward(operation).map(response => {
    const {
      response: { headers },
    } = operation.getContext()

    if (headers) {
      const authToken = headers.get("x-jwt-auth")
      const refreshToken = headers.get("x-jwt-refresh")

      if (authToken) {
        // Save auth token here.
      }

      if (refreshToken) {
        // Save refresh token here.
      }
    }

    return response
  })
})
```

**Comment by septk** [comment]
It is possible that const headers.get("x-jwt-auth") always is null?

**Comment by kellenmace** [comment]
@septk Currently, you won't be able to get the value of the `x-jwt-auth` header, since this PR has not yet been merged in. In my testing though, I was able to get both the `x-jwt-auth` and `x-jwt-refresh` header values with this code change in place.
