### ISSUE TITLE
Plugin Not working

### ISSUE THREAD

**Issue by vikramkh** [wp-graphql/wp-graphql-jwt-authentication#99]
Hi. I downloaded and activated this plugin, yet nothing changed. It added a login endpoint to graphql, but all admin requests, without or without a bearer header, return an  empty array for nodes, just like before the plugin. I know headers on my site are working because I was using the rest api with headers before. From what I gather, it should throw an error if the header is missing but I can query orders, and the nodes are just empty no matter if there is a valid header or not. Im not sure how I can provide further info. The site is khemlanimart.com and I followed Readme instructions.

**Comment by jasonbahl** [comment]
Can you provide more specifics of the steps you're taking so I can attempt to reproduce?

Also can you list your PHP and WordPress versions?

**Comment by vikramkh** [comment]
@jasonbahl Hi Jason. Yes, my apologies. I went ahead and downloaded Wp-graphql, wp-graphiql, wp-graphql-woocommerce and wp-graphql-jwt-authentication. After downloading the zip, installling it and activating it, I went to my wp-config.php and added a secret, ` define( 'GRAPHQL_JWT_AUTH_SECRET_KEY', 'my-secret-key) ` under the rest of the secrets. I then added `SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1` above ` <IfModule mod_rewrite.c> ` in my .htaccess file. All that changed was a login graphql mutation was added. But my non-admin queries still returned empty nodes. I used Graphiql desktop application to send the query:
```
query MyQuery {
  orders{
    nodes{
      id
    }
  }
}
```
and got back:
```
{
  "data": {
    "orders": {
      "nodes": []
    }
  }
}
```

I tried adding a header like:
![image](https://user-images.githubusercontent.com/22332387/86170262-76fdb300-bae0-11ea-9b8f-6cf06f0cd876.png)

And none of the headers did anything. I also tried in my react-native app, using setContext to add a header

![image](https://user-images.githubusercontent.com/22332387/86170336-9ac0f900-bae0-11ea-9288-46de06fab7bf.png)

And that returns empty nodes as well. When I try to run a mutation:
```
mutation MyMutation {
  __typename
  createOrder(input: {clientMutationId: "uniqueId"}) {
    order {
      cartHash
    }
  }
}
```
I get:
```
{
  "errors": [
    {
      "message": "User does not have the capabilities necessary to create an order.",
      "extensions": {
        "category": "user"
      },
      "locations": [
        {
          "line": 3,
          "column": 3
        }
      ],
      "path": [
        "createOrder"
      ]
    }
  ],
  "data": {
    "__typename": "RootMutation",
    "createOrder": null
  }
}
```
. Im using PHP version 7.4, WordPress version  5.4.2–en, and woocommerce version 4.1.1 . I also have different security headers set (not sure if this makes a difference since woocommerce REST API works with headers). Any way to debug what's happening?

**Comment by vikramkh** [comment]
My problem seems very similar to that of @datab in #woocommerce channel of the slack, but I don't have a httpd-app.conf file so I'm not sure what to modify

**Comment by vikramkh** [comment]
https://wp-graphql.slack.com/archives/CCYJRDN4A/p1588343824128200

**Comment by vikramkh** [comment]
Ah Ok. For anyone experiencing this problem, I modified .htaccess:
```
RewriteEngine On
RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule ^(.*) - [E=HTTP_AUTHORIZATION:%1]
```


Now I'm getting: 
```
invalid-jwt | The iss do not match with this server
```

**Comment by vikramkh** [comment]
Ok. It's because I was passing an Authorization Header. Removing the header and trying to login works and now I can get orders :). Hope this ends up helping someone cause it took me forever haha

**Comment by akshaykatale99** [comment]
hi @vikramkh , i am getting the same error while for order and customer queries. I have configured all settings and still getting the same errors. can you suggest something? thanks

**Comment by akshaykatale99** [comment]
> hi @vikramkh , i am getting the same error while for order and customer queries. I have configured all settings and still getting the same errors. can you suggest something? thanks

got it working by de-activating Jetpack plugin.
